name: Python Meter-Bus CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  setup:
    defaults:
      run:
        working-directory: '.'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "pypy-3.10"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python {{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PyMBus
        run: uv pip install ".[dev]"

      - name: Build
        run: uv build

      - name: Check
        run: make check

      - name: Test
        run: make test
